FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    procps \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://ollama.com/install.sh | sh

RUN ollama start & \
    sleep 5 && \
    ollama run llama3.2:1b && \
    kill $(pgrep ollama)

WORKDIR /app

COPY requirments_ollama.txt .

RUN pip install --no-cache-dir -r requirments_ollama.txt

COPY . /app

EXPOSE 8006

CMD ["sh", "-c", "ollama serve & uvicorn main:app --host 0.0.0.0 --port 8006 --reload"]